export enum DocumentType {
  SOCIAL_CONTRACT = 'SOCIAL_CONTRACT',
  CNPJ = 'CNPJ',
  STATE_REGISTRATION = 'STATE_REGISTRATION',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  LOGO = 'LOGO',
  STATUTE = 'STATUTE',
  OTHER = 'OTHER',
}
